### ISSUE TITLE
not a directory exception when removing a directory

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/copy-cat#11]
![IMG_20190624_155456__01](https://user-images.githubusercontent.com/9790321/60030256-9296d800-969a-11e9-90ab-769cf89bdf2e.jpg)
[copy-cat.squiddev.cc-1561388719529.log](https://github.com/SquidDev-CC/copy-cat/files/3321425/copy-cat.squiddev.cc-1561388719529.log)
Log is Google chromes JavaScript console output, I think

**Comment by SquidDev** [comment]
Mostly a note to my self, but a couple of other issues:

 - We don't detect when you go over quota. Not sure if we can report this, but worth looking in to.
 - Our CSP is entirely borked - we need to allow `data` workers, and work out what's going on with images.
 - The obvious problem of throwing `Not a directory`

**Comment by SquidDev** [comment]
I don't think this has happened again, so closing for now. Yell at me if it has and I've just never reproduced.
