### ISSUE TITLE
Rom disappeared

### ISSUE THREAD

**Issue by leveljaap** [SquidDev-CC/copy-cat#15]
Okay so I'm on mobile and I'm not sure what I did but I somehow removed rom. Also it'd be great if the filesystem on the left could be turned off because 1. its in the way and 2. its probably how I removed rom.

**Comment by SquidDev** [comment]
The ROM doesn't appear on the right hand side, and I'm unable to delete it with the `fs` API (i.e. `fs.delete("rom")`), so not sure how you achieved this. What does `fs.list("/")` in the Lua REPL display?
