### ISSUE TITLE
Cannot join on iMac and Kindle

### ISSUE THREAD

**Issue by Logotocom-OS** [SquidDev-CC/copy-cat#17]
Well, I tried accessing this project, and it seems it doesn't work on Safari or my Kindle. Only on my iPad which is weird. On my kindle it says there isn't a secure connection while my iMac says cannot connect to server. I need help.

**Comment by Logotocom-OS** [comment]
Well, I tried accessing this project, and it seems it doesn't work on Safari or my Kindle. Only on my iPad which is weird. On my kindle it says there isn't a secure connection while my iMac says cannot connect to server. I need help.

**Comment by SquidDev** [comment]
We had some server downtime over the last few days (an SSD gave up the ghost apparently), so it's possible you were trying to access it during that. Can you try again? You may want to hard refresh the page if it doesn't work the first time.
