### ISSUE TITLE
General musings

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/copy-cat#2]
Like SquidDev-CC/cloud-catcher#1, this is probably going to end up with a lot of unchecked items. But it's a start.

## General experience
 - [x] Credits page, with licenses of various sub-projects
 - [x] Information page, with links to repository and the CC wiki.
 - [x] Extend settings page to have all (relevant) CC settings.
 - [x] Save computer label to storage.
 - [x] Screenshot button. 
 - [x] Record button. We'd need to use something like [gifshot](https://yahoo.github.io/gifshot) in order to actually generate a gif, but it'd be totally possible.

## Tooling
 - [x] Produce a `web-min` package, with minified CSS and JS.
 - ~~Possibly also run Javascript through Babel, though given our dependence on recent JS features, this may not be useful.~~
 - [x] Include SHA/MD5 cachebusters inside `index.html`.

## Files
 - [x] Save filesystem to local storage. Ideally writes would be batched.
 - [x] Filesystem browser on the LHS, like Mimic and Cloud Catcher have.
 - [x] Monaco editor - again, can probably copy from Cloud Catcher.
 - ~~Ability to "mount" a filesystem from a GitHub repository and/or Gist. We'd need to display a progress bar as we fetch the entire repository, and then boot the computer afterwards.~~ I've added the ability to run arbitrary startup files via a query argument. I want to look into non-persistent filesystems first.
 - [x] Upload / download computer mount from a ZIP

## HTTP
 - [x] Add HTTP support. We can probably do without CORS for now, but we really need a strategy for it. We can run through [cors anywhere](https://cors-anywhere.herokuapp.com/), but it's a wee bit of a bodge.
 - [x] Add websocket support.

**Comment by JasonTheKitten** [comment]
Since I was the one who suggested cors anywhere, here is how I did it:
https://github.com/JasonTheKitten/Mimic/blob/e1a2ae0bb6e21ab10454b36c89bd7243bc35ccb7/scripts/apis/http.js#L48
