### ISSUE TITLE
Add ability to boot custom rom?

### ISSUE THREAD

**Issue by oxmc** [SquidDev-CC/copy-cat#25]
I think this would be a cool idea to add, a user makes a custom rom then the emulator runs the custom rom.

**Comment by SquidDev** [comment]
Agreed that this would be pretty nice. However, I think it's probably a bit too complex to add to copy-cat. As we're running on the web (and so don't have convenient access to things like local file systems), everything ends up being far more awkward than it should be.

At this point I'd recommend using a desktop emulator like [CCEmuX](https://emux.cc) or [CraftOS-PC](https://www.craftos-pc.cc/).
