### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/copy-cat#3]
Performance of the Lua VM is iffy at best, poor at worst. It'd be nice to do some profiling and see what, if anything can be improved.

A couple of things possibly worth trying
 - Different optimisation levels
 - Updating TeaVM to 0.6-SNAPSHOT. We may need to redo our buildscript as part of this.
 - Compiling to WebAssembly. This may make writing bindings a little bit harder.

We could also try using [JSweet](http://www.jsweet.org), [JWebAssembly](https://github.com/i-net-software/JWebAssembly) or [Bytecoder](https://github.com/mirkosertic/Bytecoder), and see if they have any differences in performance. Not sure how production ready either of these are though...

**Comment by JasonTheKitten** [comment]
You could also try (doppio)[https://github.com/plasma-umass/doppio]

**Comment by SquidDev** [comment]
Sadly doppio appears to be an interpreter, which means it's even slower!

> While substantially slower than a native JVM (between 24x and 42x slower on CPU-intensive  benchmarks in Google Chrome), DOPPIOJVM makes it feasible to directly reuse existing, non compute-intensive code.

[From the paper](https://plasma-umass.org/doppio-demo/paper.pdf)

**Comment by SquidDev** [comment]
I think this is unlikely to be resolved any time soon. It's as good as it's going to get, and not unmanageable.
