### ISSUE TITLE
[Feature Request] expose DOM as a peripheral to embedded computers

### ISSUE THREAD

**Issue by dimaguy** [SquidDev-CC/copy-cat#38]
Exposing the dom to a copy-cat instance as a peripheral could allow to have essentially a lua runtime running on the background, and coding a webpage in lua instead of javascript

**Comment by SquidDev** [comment]
I'm afraid I think this is out of scope - copy-cat is intended to be a ComputerCraft emulator, not a general programming environment.

You might want to check out https://github.com/fengari-lua/fengari instead, which looks closer to what you want.
