### ISSUE TITLE
os.time without "UTC" returns constant 0

### ISSUE THREAD

**Issue by JasonTheKitten** [SquidDev-CC/copy-cat#5]
This behavior may break functionality of programs such as benchmark tests, clocks, etc.

I believe that this could easily be fixed by wrapping the UTC clock with division or multiplication.

**Comment by SquidDev** [comment]
Truth be told, benchmarking scripts _really_ shouldn't be using `os.time` - `os.clock` or `os.epoch("utc")` are more reliable. But yes, really should be incrementing the time!
